// this is protobuff for Request and Response

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: proto/leader/leader.proto

package leader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// heartbeat messages
type Hb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Heartbeat             bool   `protobuf:"varint,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Ip                    string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	MembershipListVersion int32  `protobuf:"varint,3,opt,name=membershipListVersion,proto3" json:"membershipListVersion,omitempty"` // actually leadershiplistversion
}

func (x *Hb) Reset() {
	*x = Hb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leader_leader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hb) ProtoMessage() {}

func (x *Hb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_leader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hb.ProtoReflect.Descriptor instead.
func (*Hb) Descriptor() ([]byte, []int) {
	return file_proto_leader_leader_proto_rawDescGZIP(), []int{0}
}

func (x *Hb) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *Hb) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Hb) GetMembershipListVersion() int32 {
	if x != nil {
		return x.MembershipListVersion
	}
	return 0
}

type MemberList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Version int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leader_leader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_leader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_proto_leader_leader_proto_rawDescGZIP(), []int{1}
}

func (x *MemberList) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberList) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type NodeAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *NodeAddress) Reset() {
	*x = NodeAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leader_leader_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddress) ProtoMessage() {}

func (x *NodeAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_leader_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddress.ProtoReflect.Descriptor instead.
func (*NodeAddress) Descriptor() ([]byte, []int) {
	return file_proto_leader_leader_proto_rawDescGZIP(), []int{2}
}

func (x *NodeAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type LocalFileNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalFileNames []string `protobuf:"bytes,1,rep,name=localFileNames,proto3" json:"localFileNames,omitempty"`
}

func (x *LocalFileNames) Reset() {
	*x = LocalFileNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leader_leader_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalFileNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFileNames) ProtoMessage() {}

func (x *LocalFileNames) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_leader_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFileNames.ProtoReflect.Descriptor instead.
func (*LocalFileNames) Descriptor() ([]byte, []int) {
	return file_proto_leader_leader_proto_rawDescGZIP(), []int{3}
}

func (x *LocalFileNames) GetLocalFileNames() []string {
	if x != nil {
		return x.LocalFileNames
	}
	return nil
}

type StandbyHb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Heartbeat             bool   `protobuf:"varint,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Ip                    string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	MembershipListVersion int32  `protobuf:"varint,3,opt,name=membershipListVersion,proto3" json:"membershipListVersion,omitempty"`
	LeaderListVersion     int32  `protobuf:"varint,4,opt,name=leaderListVersion,proto3" json:"leaderListVersion,omitempty"`
}

func (x *StandbyHb) Reset() {
	*x = StandbyHb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leader_leader_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandbyHb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandbyHb) ProtoMessage() {}

func (x *StandbyHb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_leader_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandbyHb.ProtoReflect.Descriptor instead.
func (*StandbyHb) Descriptor() ([]byte, []int) {
	return file_proto_leader_leader_proto_rawDescGZIP(), []int{4}
}

func (x *StandbyHb) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *StandbyHb) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StandbyHb) GetMembershipListVersion() int32 {
	if x != nil {
		return x.MembershipListVersion
	}
	return 0
}

func (x *StandbyHb) GetLeaderListVersion() int32 {
	if x != nil {
		return x.LeaderListVersion
	}
	return 0
}

type NetworkMembers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members               []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	MembershipListVersion int32    `protobuf:"varint,2,opt,name=membershipListVersion,proto3" json:"membershipListVersion,omitempty"`
	Leaders               []string `protobuf:"bytes,3,rep,name=leaders,proto3" json:"leaders,omitempty"`
	LeaderListVersion     int32    `protobuf:"varint,4,opt,name=leaderListVersion,proto3" json:"leaderListVersion,omitempty"`
}

func (x *NetworkMembers) Reset() {
	*x = NetworkMembers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leader_leader_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMembers) ProtoMessage() {}

func (x *NetworkMembers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_leader_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMembers.ProtoReflect.Descriptor instead.
func (*NetworkMembers) Descriptor() ([]byte, []int) {
	return file_proto_leader_leader_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkMembers) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *NetworkMembers) GetMembershipListVersion() int32 {
	if x != nil {
		return x.MembershipListVersion
	}
	return 0
}

func (x *NetworkMembers) GetLeaders() []string {
	if x != nil {
		return x.Leaders
	}
	return nil
}

func (x *NetworkMembers) GetLeaderListVersion() int32 {
	if x != nil {
		return x.LeaderListVersion
	}
	return 0
}

type GeneralMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GeneralMessage) Reset() {
	*x = GeneralMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leader_leader_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralMessage) ProtoMessage() {}

func (x *GeneralMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leader_leader_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralMessage.ProtoReflect.Descriptor instead.
func (*GeneralMessage) Descriptor() ([]byte, []int) {
	return file_proto_leader_leader_proto_rawDescGZIP(), []int{6}
}

func (x *GeneralMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_leader_leader_proto protoreflect.FileDescriptor

var file_proto_leader_leader_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2f, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x22, 0x68, 0x0a, 0x02, 0x68, 0x62, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x34, 0x0a, 0x15, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x40, 0x0a,
	0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x27, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x62, 0x79, 0x48, 0x62,
	0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x34,
	0x0a, 0x15, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x11, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12,
	0x34, 0x0a, 0x15, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x2c, 0x0a, 0x11, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a,
	0x0e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xf6, 0x01, 0x0a, 0x06, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0a, 0x2e, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x68, 0x62, 0x1a, 0x12, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x43, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x13, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x16, 0x2e,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x6e, 0x64, 0x62, 0x79, 0x12, 0x11, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x62, 0x79, 0x48, 0x62, 0x1a, 0x16, 0x2e, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x16, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x63, 0x73, 0x34, 0x32, 0x35, 0x2f, 0x6d, 0x70, 0x2f, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_leader_leader_proto_rawDescOnce sync.Once
	file_proto_leader_leader_proto_rawDescData = file_proto_leader_leader_proto_rawDesc
)

func file_proto_leader_leader_proto_rawDescGZIP() []byte {
	file_proto_leader_leader_proto_rawDescOnce.Do(func() {
		file_proto_leader_leader_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_leader_leader_proto_rawDescData)
	})
	return file_proto_leader_leader_proto_rawDescData
}

var file_proto_leader_leader_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_leader_leader_proto_goTypes = []interface{}{
	(*Hb)(nil),             // 0: leader.hb
	(*MemberList)(nil),     // 1: leader.memberList
	(*NodeAddress)(nil),    // 2: leader.nodeAddress
	(*LocalFileNames)(nil), // 3: leader.localFileNames
	(*StandbyHb)(nil),      // 4: leader.standbyHb
	(*NetworkMembers)(nil), // 5: leader.networkMembers
	(*GeneralMessage)(nil), // 6: leader.generalMessage
}
var file_proto_leader_leader_proto_depIdxs = []int32{
	0, // 0: leader.Leader.Join:input_type -> leader.hb
	2, // 1: leader.Leader.ShowFileInDataNode:input_type -> leader.nodeAddress
	4, // 2: leader.Leader.JoinStandby:input_type -> leader.standbyHb
	6, // 3: leader.Leader.query:input_type -> leader.generalMessage
	1, // 4: leader.Leader.Join:output_type -> leader.memberList
	3, // 5: leader.Leader.ShowFileInDataNode:output_type -> leader.localFileNames
	5, // 6: leader.Leader.JoinStandby:output_type -> leader.networkMembers
	6, // 7: leader.Leader.query:output_type -> leader.generalMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_leader_leader_proto_init() }
func file_proto_leader_leader_proto_init() {
	if File_proto_leader_leader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_leader_leader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leader_leader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leader_leader_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leader_leader_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalFileNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leader_leader_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandbyHb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leader_leader_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkMembers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leader_leader_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_leader_leader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leader_leader_proto_goTypes,
		DependencyIndexes: file_proto_leader_leader_proto_depIdxs,
		MessageInfos:      file_proto_leader_leader_proto_msgTypes,
	}.Build()
	File_proto_leader_leader_proto = out.File
	file_proto_leader_leader_proto_rawDesc = nil
	file_proto_leader_leader_proto_goTypes = nil
	file_proto_leader_leader_proto_depIdxs = nil
}
